### ISSUE TITLE
Some tips on how to get it working?

### ISSUE THREAD

**Issue by madalinignisca** [woduda/kohana-dashboard#1]
Hi,

First, I'm not a Kohana or other HMVC expert, just trying to learn.

I'm trying to check out this module and I'm following the common procedure to setup a Kohana module.

I've called it in the module init in bootstrap, I've set just above the default route the mentioned route in your init and once I do that, I get 404 / requested URL / not found on this server. Even "/dashboard" doesn't works.

Any tips how to start with it?

Thank you in advance.

**Comment by madalinignisca** [comment]
Never mind, my bad, I didn't setup the modules how it should.

**Comment by woduda** [comment]
Hi, 
It is a quick development module, luck of documentation. I'll provide some examples and docs in future.
For now the best you can do is analysis of my code.
PS. default views and templates are prepared to utilise Bootstrap and jQuery. You should include them yourself in your project.

**Comment by madalinignisca** [comment]
Thank you, I managed to start with it. Also, nice that you did not include any media (css, js) assets as I wanted to handle them different with another module to automate some stuff.

Good starting point.

Thanks again.
